/// part
nme=me
class name{
   t @= """kama"""
    'name'
    ''''''
  val name = true 
  let   n : bool = l;
  try {

  }catch (e :err){
break ;
for 
while 
switch 
if( "kamau" == "kemboi")
when => n ;
val kamau => 'kamau'
  }
  return ';;;';

}
// nam
/** kama 
* 
*/
namespace name {
    "lll"
    class  me {
        let me = " "
    }
}
@part
class  name{
 
     
    let anme;
    val me  : int = "kama";

    val me = "kamau"
    var bool = false
    return "lll"
}