project {
  name = examples/async-demo
  version = "1.0.0"
  description = "A new Stratos project"
  authors = ["Your Name"]
  keywords = [examples/async-demo]
 # Keywords for dependancies search   categories = []
 # similar to crates.io  Categories  license = "MIT"
  repository = "https://github.com/yourname/examples/async-demo"
  documentation = "https://github.com/yourname/examples/async-demo"
}

build {
  entry = src/main.st
  output = build/examples/async-demo
}

dependencies = [
  # {
  #   name = "example"
  #   url = "https://github.com/example/lib"
  #   tag = "v1.0.0"
  # }
]
