project {
  name = .\examples\json-data
  version = "1.0.0"
  description = "A new Stratos project"
  authors = ["Your Name"]
  keywords = [.\examples\json-data]
 # Keywords for dependancies search   categories = []
 # similar to crates.io  Categories  license = "MIT"
  repository = "https://github.com/yourname/.\examples\json-data"
  documentation = "https://github.com/yourname/.\examples\json-data"
}

build {
  entry = src/main.st
  output = build/.\examples\json-data
}

dependencies =[
    # {
    #     name = json
    #     url = "https://github.com/stratos-lang/json"
    #     tag = "v1.0.0"
    # }
]


