project {
  name = function_definition
  version = "1.0.0"
  description = "A simple project to show Stratos Function definitions"
}

build {
  entry = src/main.st
  output = build/function_definition
}
