package main;

function main(){

   // mutable  and nullable 
   var name_first  = "kamau" ;
   //  mutable  and nullable  with explicit type
   var name_second : String  = "kamau" ;

   // imutable and nullable
   var userAge  = SomeFunction(); 
   //  imutable  and nullable  with explicit type
   var userHeight : int  = 145 ;

   // non nullable and imutable 
   var userLat  = 12.333 ; 
   // non nullable and imutable   with explicit type
   var userLong : double = 12.333 ; 
   //  non nullable and mutable
    var mutable userAngle : double = 12.333 ; 
}