project {
  name = oop-class-visibility
  version = "1.0.0"
  description = "A new Stratos project"
  authors = ["Your Name"]
  keywords = [oop-class-visibility]
 # Keywords for dependancies search   categories = []
 # similar to crates.io  Categories  license = "MIT"
  repository = "https://github.com/yourname/oop-class-visibility"
  documentation = "https://github.com/yourname/oop-class-visibility"
}

build {
  entry = src/main.st
  output = build/oop-class-visibility
}

dependencies =[
  # {
  #   name = "oop-class-visibility"
  #   url = "https://github.com/stratos-lang/oop-class-visibility"
  #   tag = "v1.0.0"
  # }
]
