package main;

fn main() {
    val x = 5;

    // If expression
    val status = if (x > 0) "Positive" else "Non-positive";
    println("Status: " + status);

    // Loop
    //println("Counting:");
    //for i in (1..=3) {
    //    println(i);
    //}

    // When expression
   // val message = when (x) {
   //     1 -> "One"
   //     5 -> "Five"
  //      else -> "Other"
  //  };
  //  println("Match: " + message);
}