project {
    name = database-example
    version = 1.0.0
    author = Stratos Team
    license = MIT
}

build {
    entry = src/main.st
    output = build/database-example
}

dependencies = [
    # {
    #     name = db
    #     url = "https://github.com/stratos-lang/db"
    #     tag = "v1.0.0"
    # }
]
