project {
  name = comments_and_documentation
  version = "1.0.0"
  description = "A simple project to show Stratos syntax comments and documentation"
}

build {
  entry = src/main.st
  output = build/comments_and_documentation
}
