/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include <iostream>
#include <fstream>
#include "app.h"


int main (int argc, char** argv) {

   std::cout << "Booting stratos compiler" << std::endl;

    std::fstream my_file;
    std::string filePath ="/home/kamau/Development/Stratos/compiler/native/src/sample/variable.st";

    std::ifstream file(filePath);
    if (file.is_open()) {
        std::string line;
        while (std::getline(file, line)) {
            // using printf() in all tests for consistency
            printf("%s", line.c_str());

        }
        file.close();
    }

    return 0;
}
